CREATE TABLE study_session_snapshot_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    flashcard_id BIGINT NOT NULL,
    item_order INT NOT NULL,
    front_text VARCHAR(300) NOT NULL,
    back_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE study_session_snapshot_items
ADD CONSTRAINT fk_study_session_snapshot_items_session
FOREIGN KEY (session_id) REFERENCES study_sessions (id);

ALTER TABLE study_session_snapshot_items
ADD CONSTRAINT fk_study_session_snapshot_items_flashcard
FOREIGN KEY (flashcard_id) REFERENCES flashcards (id);

ALTER TABLE study_session_snapshot_items
ADD CONSTRAINT chk_study_session_snapshot_items_item_order
CHECK (item_order >= 0);

ALTER TABLE study_session_snapshot_items
ADD CONSTRAINT uq_study_session_snapshot_items_session_item_order
UNIQUE (session_id, item_order);

CREATE INDEX idx_study_session_snapshot_items_session_id ON study_session_snapshot_items (session_id);
CREATE INDEX idx_study_session_snapshot_items_flashcard_id ON study_session_snapshot_items (flashcard_id);
