CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    normalized_email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE app_users
ADD CONSTRAINT chk_app_users_email_not_blank
CHECK (TRIM(email) <> '');

ALTER TABLE app_users
ADD CONSTRAINT chk_app_users_normalized_email_not_blank
CHECK (TRIM(normalized_email) <> '');

ALTER TABLE app_users
ADD CONSTRAINT chk_app_users_password_hash_not_blank
CHECK (TRIM(password_hash) <> '');

CREATE UNIQUE INDEX uq_app_users_normalized_email
ON app_users (normalized_email);

CREATE TABLE auth_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    last_used_at TIMESTAMP,
    replaced_by_token_hash VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE auth_refresh_tokens
ADD CONSTRAINT fk_auth_refresh_tokens_user
FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE auth_refresh_tokens
ADD CONSTRAINT chk_auth_refresh_tokens_hash_not_blank
CHECK (TRIM(token_hash) <> '');

ALTER TABLE auth_refresh_tokens
ADD CONSTRAINT chk_auth_refresh_tokens_expires_at
CHECK (expires_at > created_at);

CREATE UNIQUE INDEX uq_auth_refresh_tokens_token_hash
ON auth_refresh_tokens (token_hash);

CREATE INDEX idx_auth_refresh_tokens_user_id
ON auth_refresh_tokens (user_id);

CREATE INDEX idx_auth_refresh_tokens_expires_at
ON auth_refresh_tokens (expires_at);
