CREATE TABLE user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    theme_mode VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    study_auto_play_audio BOOLEAN NOT NULL DEFAULT FALSE,
    study_cards_per_session INTEGER NOT NULL DEFAULT 10,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_settings
ADD CONSTRAINT fk_user_settings_user
FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE user_settings
ADD CONSTRAINT uq_user_settings_user_id UNIQUE (user_id);

ALTER TABLE user_settings
ADD CONSTRAINT chk_user_settings_theme_mode
CHECK (theme_mode IN ('SYSTEM', 'LIGHT', 'DARK'));

ALTER TABLE user_settings
ADD CONSTRAINT chk_user_settings_study_cards_per_session
CHECK (study_cards_per_session BETWEEN 5 AND 20);

INSERT INTO user_settings (user_id, theme_mode, study_auto_play_audio, study_cards_per_session)
SELECT id, theme_mode, study_auto_play_audio, study_cards_per_session
FROM app_users;

ALTER TABLE app_users DROP COLUMN theme_mode;
ALTER TABLE app_users DROP COLUMN study_auto_play_audio;
ALTER TABLE app_users DROP COLUMN study_cards_per_session;
