CREATE TABLE folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(400) NOT NULL DEFAULT '',
    color_hex VARCHAR(16) NOT NULL,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'system',
    deleted_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE INDEX idx_folders_updated_at ON folders (updated_at DESC);
CREATE INDEX idx_folders_deleted_at ON folders (deleted_at);
CREATE INDEX idx_folders_name ON folders (name);
