CREATE TABLE decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120),
    description VARCHAR(400) NOT NULL DEFAULT '',
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'system',
    deleted_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

ALTER TABLE decks
ADD CONSTRAINT fk_decks_folder
FOREIGN KEY (folder_id) REFERENCES folders (id);

ALTER TABLE decks
ADD CONSTRAINT chk_decks_name_not_blank
CHECK (TRIM(name) <> '');

ALTER TABLE decks
ADD CONSTRAINT chk_decks_active_normalized_name
CHECK (deleted_at IS NOT NULL OR normalized_name IS NOT NULL);

CREATE UNIQUE INDEX uq_decks_folder_active_normalized_name
ON decks (folder_id, normalized_name);

CREATE INDEX idx_decks_deleted_at ON decks (deleted_at);
CREATE INDEX idx_decks_folder_id ON decks (folder_id);
CREATE INDEX idx_decks_name ON decks (name);
CREATE INDEX idx_decks_updated_at ON decks (updated_at);
