CREATE TABLE flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    front_text VARCHAR(300) NOT NULL,
    back_text VARCHAR(2000) NOT NULL,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'system',
    deleted_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

ALTER TABLE flashcards
ADD CONSTRAINT fk_flashcards_deck
FOREIGN KEY (deck_id) REFERENCES decks (id);

ALTER TABLE flashcards
ADD CONSTRAINT chk_flashcards_front_text_not_blank
CHECK (TRIM(front_text) <> '');

ALTER TABLE flashcards
ADD CONSTRAINT chk_flashcards_back_text_not_blank
CHECK (TRIM(back_text) <> '');

CREATE INDEX idx_flashcards_deleted_at ON flashcards (deleted_at);
CREATE INDEX idx_flashcards_deck_id ON flashcards (deck_id);
CREATE INDEX idx_flashcards_deck_deleted_at ON flashcards (deck_id, deleted_at);
CREATE INDEX idx_flashcards_front_text ON flashcards (front_text);
CREATE INDEX idx_flashcards_updated_at ON flashcards (updated_at);
