CREATE TABLE study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    active_mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    seed INT NOT NULL DEFAULT 37,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'system',
    deleted_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

ALTER TABLE study_sessions
ADD CONSTRAINT fk_study_sessions_deck
FOREIGN KEY (deck_id) REFERENCES decks (id);

ALTER TABLE study_sessions
ADD CONSTRAINT chk_study_sessions_active_mode
CHECK (active_mode IN ('review', 'match', 'guess', 'recall', 'fill'));

ALTER TABLE study_sessions
ADD CONSTRAINT chk_study_sessions_status
CHECK (status IN ('ACTIVE', 'COMPLETED'));

ALTER TABLE study_sessions
ADD CONSTRAINT chk_study_sessions_seed
CHECK (seed >= 0);

ALTER TABLE study_sessions
ADD CONSTRAINT chk_study_sessions_completed_at_after_started_at
CHECK (completed_at IS NULL OR completed_at >= started_at);

CREATE INDEX idx_study_sessions_deck_id ON study_sessions (deck_id);
CREATE INDEX idx_study_sessions_active_mode ON study_sessions (active_mode);
CREATE INDEX idx_study_sessions_status ON study_sessions (status);
CREATE INDEX idx_study_sessions_deleted_at ON study_sessions (deleted_at);
CREATE INDEX idx_study_sessions_created_at ON study_sessions (created_at);

CREATE TABLE study_session_mode_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    mode VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    current_index INT NOT NULL DEFAULT 0,
    total_units INT NOT NULL DEFAULT 0,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE study_session_mode_states
ADD CONSTRAINT fk_study_session_mode_states_session
FOREIGN KEY (session_id) REFERENCES study_sessions (id);

ALTER TABLE study_session_mode_states
ADD CONSTRAINT uq_study_session_mode_states_session_mode
UNIQUE (session_id, mode);

ALTER TABLE study_session_mode_states
ADD CONSTRAINT chk_study_session_mode_states_mode
CHECK (mode IN ('review', 'match', 'guess', 'recall', 'fill'));

ALTER TABLE study_session_mode_states
ADD CONSTRAINT chk_study_session_mode_states_status
CHECK (status IN ('ACTIVE', 'COMPLETED'));

ALTER TABLE study_session_mode_states
ADD CONSTRAINT chk_study_session_mode_states_counts
CHECK (current_index >= 0 AND total_units >= 0);

ALTER TABLE study_session_mode_states
ADD CONSTRAINT chk_study_session_mode_states_completed_at_after_started_at
CHECK (completed_at IS NULL OR completed_at >= started_at);

CREATE INDEX idx_study_session_mode_states_session_id ON study_session_mode_states (session_id);
CREATE INDEX idx_study_session_mode_states_mode ON study_session_mode_states (mode);
CREATE INDEX idx_study_session_mode_states_status ON study_session_mode_states (status);
