CREATE TABLE study_session_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode_state_id BIGINT NOT NULL,
    flashcard_id BIGINT NOT NULL,
    item_order INT NOT NULL,
    front_text VARCHAR(300) NOT NULL,
    back_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE study_session_items
ADD CONSTRAINT fk_study_session_items_mode_state
FOREIGN KEY (mode_state_id) REFERENCES study_session_mode_states (id);

ALTER TABLE study_session_items
ADD CONSTRAINT fk_study_session_items_flashcard
FOREIGN KEY (flashcard_id) REFERENCES flashcards (id);

ALTER TABLE study_session_items
ADD CONSTRAINT chk_study_session_items_item_order
CHECK (item_order >= 0);

ALTER TABLE study_session_items
ADD CONSTRAINT uq_study_session_items_mode_state_item_order
UNIQUE (mode_state_id, item_order);

CREATE INDEX idx_study_session_items_mode_state_id ON study_session_items (mode_state_id);
CREATE INDEX idx_study_session_items_flashcard_id ON study_session_items (flashcard_id);
