CREATE TABLE flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id BIGINT NOT NULL,
    front_text VARCHAR(300) NOT NULL,
    back_text VARCHAR(2000) NOT NULL,
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'system',
    deleted_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

ALTER TABLE flashcards
ADD CONSTRAINT fk_flashcards_folder
FOREIGN KEY (folder_id) REFERENCES folders (id);

CREATE INDEX idx_flashcards_folder_id ON flashcards (folder_id);
CREATE INDEX idx_flashcards_deleted_at ON flashcards (deleted_at);
CREATE INDEX idx_flashcards_front_text ON flashcards (front_text);
