CREATE TABLE study_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    client_event_id VARCHAR(120) NOT NULL,
    client_sequence INT NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    target_index INT,
    target_tile_id BIGINT,
    left_tile_id BIGINT,
    right_tile_id BIGINT,
    is_correct BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE study_attempts
ADD CONSTRAINT fk_study_attempts_session
FOREIGN KEY (session_id) REFERENCES study_sessions (id);

ALTER TABLE study_attempts
ADD CONSTRAINT chk_study_attempts_client_sequence
CHECK (client_sequence >= 0);

ALTER TABLE study_attempts
ADD CONSTRAINT chk_study_attempts_client_event_id_not_blank
CHECK (TRIM(client_event_id) <> '');

ALTER TABLE study_attempts
ADD CONSTRAINT chk_study_attempts_event_type_not_blank
CHECK (TRIM(event_type) <> '');

ALTER TABLE study_attempts
ADD CONSTRAINT chk_study_attempts_event_type
CHECK (
    event_type IN (
        'review.next',
        'review.previous',
        'review.gotoIndex',
        'match.selectLeft',
        'match.selectRight'
    )
);

ALTER TABLE study_attempts
ADD CONSTRAINT chk_study_attempts_target_index
CHECK (target_index IS NULL OR target_index >= 0);

ALTER TABLE study_attempts
ADD CONSTRAINT uq_study_attempts_session_event_id
UNIQUE (session_id, client_event_id);

ALTER TABLE study_attempts
ADD CONSTRAINT uq_study_attempts_session_sequence
UNIQUE (session_id, client_sequence);

CREATE INDEX idx_study_attempts_session_id ON study_attempts (session_id);
CREATE INDEX idx_study_attempts_event_type ON study_attempts (event_type);
