CREATE TABLE decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(400) NOT NULL DEFAULT '',
    created_by VARCHAR(120) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(120) NOT NULL DEFAULT 'system',
    deleted_by VARCHAR(120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

ALTER TABLE decks
ADD CONSTRAINT fk_decks_folder
FOREIGN KEY (folder_id) REFERENCES folders (id);

CREATE INDEX idx_decks_folder_id ON decks (folder_id);
CREATE INDEX idx_decks_deleted_at ON decks (deleted_at);
CREATE INDEX idx_decks_name ON decks (name);

ALTER TABLE flashcards
ADD COLUMN deck_id BIGINT;

INSERT INTO decks (
    folder_id,
    name,
    description,
    created_by,
    updated_by
)
SELECT
    source.folder_id,
    'Default Deck',
    'Migrated from folder-level flashcards.',
    'system',
    'system'
FROM (
    SELECT DISTINCT flashcard.folder_id
    FROM flashcards flashcard
    WHERE flashcard.deleted_at IS NULL
) source
WHERE source.folder_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM decks deck
      WHERE deck.folder_id = source.folder_id
        AND LOWER(deck.name) = LOWER('Default Deck')
        AND deck.deleted_at IS NULL
  );

UPDATE flashcards flashcard
SET deck_id = (
    SELECT deck.id
    FROM decks deck
    WHERE deck.folder_id = flashcard.folder_id
      AND LOWER(deck.name) = LOWER('Default Deck')
      AND deck.deleted_at IS NULL
    FETCH FIRST 1 ROW ONLY
)
WHERE flashcard.deck_id IS NULL;

ALTER TABLE flashcards
ALTER COLUMN deck_id SET NOT NULL;

ALTER TABLE flashcards
ADD CONSTRAINT fk_flashcards_deck
FOREIGN KEY (deck_id) REFERENCES decks (id);

CREATE INDEX idx_flashcards_deck_id ON flashcards (deck_id);

ALTER TABLE flashcards DROP CONSTRAINT fk_flashcards_folder;
DROP INDEX IF EXISTS idx_flashcards_folder_id;
ALTER TABLE flashcards DROP COLUMN folder_id;
