CREATE TABLE match_session_tiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    pair_key INT NOT NULL,
    side VARCHAR(10) NOT NULL,
    label_text VARCHAR(2000) NOT NULL,
    tile_order INT NOT NULL,
    is_matched BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE match_session_tiles
ADD CONSTRAINT fk_match_session_tiles_session
FOREIGN KEY (session_id) REFERENCES study_sessions (id);

ALTER TABLE match_session_tiles
ADD CONSTRAINT chk_match_session_tiles_pair_key
CHECK (pair_key >= 0);

ALTER TABLE match_session_tiles
ADD CONSTRAINT chk_match_session_tiles_side
CHECK (side IN ('LEFT', 'RIGHT'));

ALTER TABLE match_session_tiles
ADD CONSTRAINT chk_match_session_tiles_label_text_not_blank
CHECK (TRIM(label_text) <> '');

ALTER TABLE match_session_tiles
ADD CONSTRAINT chk_match_session_tiles_tile_order
CHECK (tile_order >= 0);

ALTER TABLE match_session_tiles
ADD CONSTRAINT uq_match_session_tiles_session_side_pair_key
UNIQUE (session_id, side, pair_key);

ALTER TABLE match_session_tiles
ADD CONSTRAINT uq_match_session_tiles_session_side_tile_order
UNIQUE (session_id, side, tile_order);

ALTER TABLE match_session_tiles
ADD CONSTRAINT uq_match_session_tiles_session_id_id
UNIQUE (session_id, id);

CREATE INDEX idx_match_session_tiles_session_id ON match_session_tiles (session_id);
CREATE INDEX idx_match_session_tiles_session_side ON match_session_tiles (session_id, side);
CREATE INDEX idx_match_session_tiles_session_matched ON match_session_tiles (session_id, is_matched);
CREATE INDEX idx_match_session_tiles_updated_at ON match_session_tiles (updated_at);
