CREATE TABLE match_session_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE,
    selected_left_tile_id BIGINT,
    selected_right_tile_id BIGINT,
    interaction_locked BOOLEAN NOT NULL DEFAULT FALSE,
    feedback_status VARCHAR(20),
    feedback_left_tile_id BIGINT,
    feedback_right_tile_id BIGINT,
    feedback_until TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_session
FOREIGN KEY (session_id) REFERENCES study_sessions (id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_selected_left_tile
FOREIGN KEY (selected_left_tile_id) REFERENCES match_session_tiles (id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_selected_left_tile_same_session
FOREIGN KEY (session_id, selected_left_tile_id) REFERENCES match_session_tiles (session_id, id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_selected_right_tile
FOREIGN KEY (selected_right_tile_id) REFERENCES match_session_tiles (id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_selected_right_tile_same_session
FOREIGN KEY (session_id, selected_right_tile_id) REFERENCES match_session_tiles (session_id, id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_feedback_left_tile
FOREIGN KEY (feedback_left_tile_id) REFERENCES match_session_tiles (id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_feedback_left_tile_same_session
FOREIGN KEY (session_id, feedback_left_tile_id) REFERENCES match_session_tiles (session_id, id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_feedback_right_tile
FOREIGN KEY (feedback_right_tile_id) REFERENCES match_session_tiles (id);

ALTER TABLE match_session_states
ADD CONSTRAINT fk_match_session_states_feedback_right_tile_same_session
FOREIGN KEY (session_id, feedback_right_tile_id) REFERENCES match_session_tiles (session_id, id);

ALTER TABLE match_session_states
ADD CONSTRAINT chk_match_session_states_feedback_status
CHECK (feedback_status IS NULL OR feedback_status IN ('SUCCESS', 'ERROR'));

ALTER TABLE match_session_states
ADD CONSTRAINT chk_match_session_states_version
CHECK (version >= 0);

ALTER TABLE match_session_states
ADD CONSTRAINT chk_match_session_states_feedback_pair
CHECK (
    (feedback_left_tile_id IS NULL AND feedback_right_tile_id IS NULL)
    OR (feedback_left_tile_id IS NOT NULL AND feedback_right_tile_id IS NOT NULL)
);

CREATE INDEX idx_match_session_states_feedback_until ON match_session_states (feedback_until);
CREATE INDEX idx_match_session_states_session_id ON match_session_states (session_id);
CREATE INDEX idx_match_session_states_updated_at ON match_session_states (updated_at);
